#!/bin/sh

 # 1) This ensures our peers continue to report their Wireguard
 #    assigned IPs while connected to the VPN. This is required
 #    for their traffic to get routed correctly by the firewall
 #    rules we crafted earlier with pf.
 /usr/sbin/sysctl -w net.inet.ip.forwarding=1
 /usr/sbin/sysctl -w net.inet6.ip6.forwarding=1

 # 2) Preparing the directory where we'll persist the pf tokens
 #    generated by Step (3) & (4). That token can then be used by
 #    our postdown.sh script to remove the routing rules when
 #    Wireguard is shut down.
 mkdir -p /usr/local/var/run/wireguard
 chmod 700 /usr/local/var/run/wireguard

 # 3) Dynamically add the IPv4 NAT rule, enable the firewall,
 #    increase its reference count (-E), and persist the reference
 #    token generated by the command into
 #    pf_wireguard_token_ipv4_token.txt, which postdown.sh will
 #    reference when Wireguard is shut down.
 echo 'nat on en0 from 10.0.10.1/24 to any -> (en0)' | \
         pfctl -a com.apple/wireguard_ipv4 -Ef - 2>&1 | \
         grep 'Token' | \
         sed 's%Token : \(.*\)%\1%' > /usr/local/var/run/wireguard/pf_wireguard_ipv4_token.txt
 IPV4_TOKEN=`sudo cat /usr/local/var/run/wireguard/pf_wireguard_ipv4_token.txt`
 echo "Added PF IPv4 NAT traffic routing rule with token: ${IPV4_TOKEN}"

 # 4) Dynamically add the IPv6 NAT rule, enable the firewall,
 #    increase its reference count (-E), and persist the reference
 #    token generated by the command into
 #    pf_wireguard_token_ipv6_token.txt, which postdown.sh will
 #    reference when Wireguard is shut down.
 echo 'nat on en0 from fd77:77:77:77::1/112 to any -> (en0)' | \
         pfctl -a com.apple/wireguard_ipv6 -Ef - 2>&1 | \
         grep 'Token' | \
         sed 's%Token : \(.*\)%\1%' > /usr/local/var/run/wireguard/pf_wireguard_ipv6_token.txt
 IPV6_TOKEN=`sudo cat /usr/local/var/run/wireguard/pf_wireguard_ipv6_token.txt`
 echo "Added PF IPv6 NAT traffic routing rule with token: ${IPV6_TOKEN}"
